### PR TITLE
latest, mostly working

### PR DESCRIPTION
**Pull request by machenmusik**
(but models currently aren't loading, not an aframe-ar issue;
I only updated index.html, not cesium.html)

### CODE REVIEW

**Comment by machenmusik** [comment]
turns out this was using old-style animation, fixed it now

**Comment by urish** [comment]
Lovely! You brought the Dino and the fox back to live :-)

What else is missing?

**Comment by urish** [comment]
Hi @machenmusik , thanks again for your hard work on this! Any reason we need a-frame from master and not 1.0.4?

**Comment by machenmusik** [comment]
I think there were fixes for hit test and/or planes

**Pull request merged**
